// World capitals + major cities — used as Autocomplete suggestions.
// Users can also type any city not in this list (freeSolo mode).
const CITIES = [
    // Middle East & North Africa
    "Gaza", "Cairo", "Alexandria", "Giza", "Amman", "Irbid", "Zarqa",
    "Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar",
    "Dubai", "Abu Dhabi", "Sharjah", "Ajman",
    "Kuwait City", "Doha", "Manama", "Muscat", "Salalah",
    "Beirut", "Tripoli", "Sidon",
    "Damascus", "Aleppo", "Homs", "Latakia",
    "Baghdad", "Basra", "Mosul", "Erbil",
    "Sanaa", "Aden",
    "Benghazi", "Misrata",
    "Tunis", "Sfax", "Sousse",
    "Algiers", "Oran", "Constantine",
    "Casablanca", "Rabat", "Fes", "Marrakech", "Agadir",
    "Nouakchott",
    "Khartoum", "Omdurman", "Port Sudan",

    // Turkey
    "Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Gaziantep",

    // Europe
    "London", "Birmingham", "Manchester", "Glasgow", "Edinburgh",
    "Paris", "Lyon", "Marseille", "Toulouse", "Bordeaux", "Nice",
    "Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart", "Dusseldorf",
    "Madrid", "Barcelona", "Valencia", "Seville", "Bilbao",
    "Rome", "Milan", "Naples", "Turin", "Florence", "Venice", "Bologna",
    "Amsterdam", "Rotterdam", "The Hague",
    "Brussels", "Antwerp", "Ghent",
    "Vienna", "Graz", "Salzburg",
    "Zurich", "Geneva", "Basel", "Bern",
    "Stockholm", "Gothenburg", "Malmo",
    "Oslo", "Bergen",
    "Copenhagen", "Aarhus",
    "Helsinki", "Tampere",
    "Warsaw", "Krakow", "Lodz", "Wroclaw",
    "Prague", "Brno",
    "Budapest", "Debrecen",
    "Lisbon", "Porto",
    "Athens", "Thessaloniki",
    "Bucharest", "Cluj-Napoca",
    "Sofia", "Plovdiv",
    "Zagreb", "Split",
    "Belgrade", "Novi Sad",
    "Kyiv", "Kharkiv", "Odessa", "Lviv",
    "Minsk",
    "Chisinau",
    "Vilnius", "Riga", "Tallinn",
    "Reykjavik",
    "Dublin", "Cork",
    "Valletta",
    "Nicosia",
    "Luxembourg",
    "Monaco",
    "Andorra la Vella",
    "Vaduz",
    "San Marino",
    "Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan",

    // Americas
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
    "Austin", "Jacksonville", "Fort Worth", "Columbus", "Indianapolis",
    "Charlotte", "San Francisco", "Seattle", "Denver", "Nashville",
    "Oklahoma City", "El Paso", "Las Vegas", "Portland", "Memphis",
    "Boston", "Atlanta", "Miami", "Minneapolis", "New Orleans",
    "Washington", "Baltimore", "Detroit", "Milwaukee",
    "Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa",
    "Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana",
    "Havana", "Kingston", "Port-au-Prince", "Santo Domingo",
    "Guatemala City", "San Salvador", "Tegucigalpa", "Managua",
    "Panama City",
    "Bogota", "Medellin", "Cali", "Barranquilla",
    "Caracas", "Maracaibo",
    "Lima", "Arequipa",
    "Quito", "Guayaquil",
    "La Paz", "Santa Cruz",
    "Asuncion",
    "Santiago", "Valparaiso",
    "Buenos Aires", "Cordoba", "Rosario", "Mendoza",
    "Montevideo",
    "Brasilia", "Sao Paulo", "Rio de Janeiro", "Salvador", "Fortaleza",
    "Manaus", "Recife", "Porto Alegre", "Belem", "Curitiba",
    "Georgetown", "Paramaribo", "Cayenne",

    // Asia
    "Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Fukuoka", "Kyoto",
    "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Tianjin", "Chongqing",
    "Wuhan", "Chengdu", "Nanjing", "Hangzhou", "Xi'an", "Dongguan",
    "Seoul", "Busan", "Incheon", "Daegu",
    "Bangkok", "Chiang Mai", "Pattaya", "Phuket",
    "Singapore",
    "Kuala Lumpur", "George Town", "Johor Bahru",
    "Jakarta", "Surabaya", "Bandung", "Medan",
    "Manila", "Cebu", "Davao",
    "Hanoi", "Ho Chi Minh City", "Da Nang",
    "Phnom Penh", "Vientiane", "Naypyidaw", "Yangon",
    "Dhaka", "Chittagong",
    "Colombo", "Kandy",
    "Kathmandu",
    "Thimphu",
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai",
    "Kolkata", "Surat", "Pune", "Jaipur",
    "Karachi", "Lahore", "Faisalabad", "Islamabad", "Rawalpindi",
    "Kabul", "Kandahar",
    "Tehran", "Mashhad", "Isfahan", "Tabriz", "Shiraz",
    "Tashkent", "Samarkand",
    "Almaty", "Astana",
    "Bishkek", "Dushanbe", "Ashgabat",
    "Baku", "Tbilisi", "Yerevan",
    "Ulaanbaatar",
    "Pyongyang",
    "Taipei", "Kaohsiung",
    "Hong Kong", "Macau",
    "Dili",
    "Bandar Seri Begawan",

    // Africa
    "Nairobi", "Mombasa",
    "Lagos", "Abuja", "Kano", "Ibadan",
    "Accra", "Kumasi",
    "Addis Ababa", "Dire Dawa",
    "Dar es Salaam", "Dodoma",
    "Kampala",
    "Kigali",
    "Bujumbura",
    "Kinshasa", "Lubumbashi",
    "Brazzaville",
    "Luanda", "Huambo",
    "Lusaka", "Ndola",
    "Harare", "Bulawayo",
    "Lilongwe", "Blantyre",
    "Maputo",
    "Antananarivo",
    "Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth",
    "Windhoek",
    "Gaborone",
    "Maseru",
    "Mbabane",
    "Mogadishu",
    "Djibouti",
    "Asmara",
    "Libreville",
    "Yaounde", "Douala",
    "Bangui",
    "N'Djamena",
    "Niamey",
    "Ouagadougou",
    "Bamako",
    "Conakry",
    "Freetown",
    "Monrovia",
    "Abidjan", "Yamoussoukro",
    "Dakar",
    "Banjul",
    "Bissau",
    "Praia",

    // Oceania
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide",
    "Canberra", "Gold Coast", "Newcastle", "Hobart",
    "Auckland", "Wellington", "Christchurch",
    "Port Moresby",
    "Suva",
    "Nuku'alofa",
    "Apia",
    "Honiara",
    "Port Vila",
    "Funafuti",
    "Tarawa",
    "Majuro",
    "Palikir",
    "Ngerulmud",
];

export default CITIES;
